pipeline:
  identifier: Build_senthilhns_gosample_1727188194726
  name: default
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - stepGroup:
                  identifier: Stage__null6133be
                  name: Print Working Directory
                  steps:
                    - step:
                        identifier: shfce0d3
                        name: sh
                        spec:
                          command: " echo \"Current working directory: $(pwd)\"  "
                          image: alpine
                          shell: Sh
                        timeout: ""
                        type: Run
                  timeout: ""
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
